apiVersion: apps/v1
kind: Deployment
metadata:
  name: golib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golib
  template:
    metadata:
      labels:
        app: golib
    spec:
      containers:
      - name: golib
        image: anandu12345/repository:tag
        env:
        - name: DB_Config
          valueFrom:
            configMapKeyRef:
              name: golib-config
              key: DB_Config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: golib-config
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: golib
  type: LoadBalancer
